SpinningFish.Web/Areas/Admin/Controllers/UsersController.cs
namespace SpinningFish.Web.Areas.Admin.Controllers
{
    using Data.Models;
    using Infrastructure.Extensions;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using Models.Users;
    using Services.Admin;
    using System.Linq;
    using System.Threading.Tasks;

    public class UsersController : BaseAdminController
    {
        private readonly IAdminUserService users;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<User> userManager;

        public UsersController(
            IAdminUserService users,
            UserManager<User> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            this.users = users;
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var allUsers = await this.users.AllAsync();
            var allRoles = await this.roleManager
                .Roles
                .Select(r => new SelectListItem
                {
                    Text = r.Name,
                    Value = r.Name 
                })
                .ToListAsync();

            return this.View(new UserListingsViewModel
            {
                Users = allUsers,
                Roles = allRoles
            });
        }

        [HttpPost]
        public async Task<IActionResult> AddToRole(AddUserToRoleFormModel model)
        {
            var roleExists = await this.roleManager.RoleExistsAsync(model.Role);
            var user = await this.userManager.FindByIdAsync(model.UserId);
            var userExists = user != null;

            if (!roleExists || !userExists)
            {
                ModelState.AddModelError(string.Empty, "Invalid identity details.");
            }

            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Index));
            }

            await this.userManager.AddToRoleAsync(user, model.Role);

            TempData.AddSuccessMessage($"User {user.UserName} successfull added to the {model.Role} role.");
            return RedirectToAction(nameof(Index));

        }
    }
}

SpinningFish.Web/Areas/Shop/Controllers/BrandsController.cs
namespace SpinningFish.Web.Areas.Shop.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Services.Shop;
    using System.Threading.Tasks;

    public class BrandsController : BaseShopController
    {
        private readonly IBrandService brands;

        public BrandsController(IBrandService brands)
        {
            this.brands = brands;
        }

        public async Task<IActionResult>  Index()
        {
            var allBrands = await this.brands.AllListingAsync();
            return this.View(allBrands);
        }

        


    }
}

SpinningFish.Web/Areas/Shop/Controllers/ReelsController.cs
namespace SpinningFish.Web.Areas.Shop.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Services.Shop;
    using System.Threading.Tasks;

    public class ReelsController : BaseShopController
    {
        private readonly IReelService reels;
        private readonly IBrandService brands;

        public ReelsController(
            IReelService reels, 
            IBrandService brands)
        {
            this.reels = reels;
            this.brands = brands;
        }

        public async Task<IActionResult> All(int id)
        {
            var allReels = await this.reels.AllReelsByIdBrandAsync(id);
            
            return this.View(allReels);
        }

        public async Task<IActionResult> Details(int id)
        {
            var allReels = await this.reels.DetailsReelByIdAsync(id);

            return this.View(allReels);
        }
    }
}

SpinningFish.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Spinning Reels SW</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-spacelab.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Spinning Reels SW</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a class="btn btn-primary" asp-area="Shop" asp-controller="Brands" asp-action="Index">Brands</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>

                        @if (User.IsInRole(WebConstants.AdministratorRole))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin Panel <span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a></li>
                                    <li><a asp-area="Admin" asp-controller="Brands" asp-action="Index">Brands</a></li>
                                    <li><a asp-area="Admin" asp-controller="Reels" asp-action="Index">Reels</a></li>

                                </ul>
                            </li>

                        }
</ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @if (TempData.ContainsKey(WebConstants.TempDataSuccessMessageKey))
        {
            <div class="alert alert-success">
                @TempData[WebConstants.TempDataSuccessMessageKey]
            </div>
        }

        @if (TempData.ContainsKey(WebConstants.TempDataErrorMessageKey))
        {
            <div class="alert alert-danger">
                @TempData[WebConstants.TempDataErrorMessageKey]
            </div>
        }

        @RenderBody()
        <hr/>
        <footer>
            <p style="text-align: center"><strong>&copy; 2017 - Spinning Reels SW</strong></p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>
    
@RenderSection("Scripts", required: false)
</body>
</html>