SpinningFish.Web/Areas/Admin/Controllers/ReelsController.cs
namespace SpinningFish.Web.Areas.Admin.Controllers
{
    using Infrastructure.Extensions;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Models.Shop;
    using Services.Admin;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    public class ReelsController : BaseAdminController
    {
        private readonly IAdminReelService reels;
        private readonly IAdminBrandService brands;

        public ReelsController(
            IAdminReelService reels, 
            IAdminBrandService brands)
        {
            this.reels = reels;
            this.brands = brands;
        }

        public async Task<IActionResult> Index()
        {
            var allReels = await this.reels.AllListindAsync();
            return this.View(allReels);
        }

        public ActionResult Create()
            => this.View(new ReelFormModel
            {
                АddedOnDate = DateTime.UtcNow,
                Brands = this.GetBrandsListItem()
            });
        
        [HttpPost]
        public async Task<IActionResult> Create(ReelFormModel reelModel)
        {
            if (!this.ModelState.IsValid)
            {
                reelModel.Brands = this.GetBrandsListItem();
                return this.View(reelModel);
            }

            var image = await reelModel.Image.ToByteArrayAsync();

            await this.reels.Create(
                reelModel.Model,
                reelModel.Description,
                reelModel.Details,
                reelModel.VideoId,
                reelModel.АddedOnDate,
                reelModel.Price,
                reelModel.Quantity,
                reelModel.Category,
                image,
                reelModel.BrandId);

            this.TempData.AddSuccessMessage($"Reel {reelModel.Model} created successfully.");

            return this.RedirectToAction(nameof(this.Index));
        }

        public IActionResult Edit(int id)
        {
            var reel = this.reels.ById(id);

            if (reel == null)
            {
                return this.NotFound();
            }

            return this.View(new ReelEditFormModel
            {
                Model = reel.Model,
                Description = reel.Description,
                Details = reel.Details,
                VideoId = reel.VideoId,
                АddedOnDate = reel.АddedOnDate,
                Price = reel.Price,
                Quantity = reel.Quantity,
                Category = reel.Category
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, ReelEditFormModel reelModel)
        {
            if (!ModelState.IsValid)
            {
                return this.View(reelModel);
            }

            await this.reels.Edit(
                id,
                reelModel.Model,
                reelModel.Description,
                reelModel.Details,
                reelModel.VideoId ,
                reelModel.АddedOnDate ,
                reelModel.Price ,
                reelModel.Quantity ,
                reelModel.Category);

            return RedirectToAction(nameof(this.Index));
        }

        public IActionResult Delete(int id) => this.View(id);

        public async Task<IActionResult> Destroy(int id)
        {
            await this.reels.Delete(id);

            return this.RedirectToAction(nameof(this.Index));
        }

        private  IEnumerable<SelectListItem> GetBrandsListItem()
            => this.brands
                .All()
                .Select(b => new SelectListItem
                {
                    Text = b.Name,
                    Value = b.Id.ToString()
                });
    }
}

SpinningFish.Web/Areas/Shop/Controllers/BrandsController.cs
namespace SpinningFish.Web.Areas.Shop.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Services.Shop;
    using System.Threading.Tasks;

    public class BrandsController : BaseShopController
    {
        private readonly IBrandService brands;

        public BrandsController(IBrandService brands)
        {
            this.brands = brands;
        }

        public async Task<IActionResult>  Index()
        {
            var allBrands = await this.brands.AllListingAsync();
            return this.View(allBrands);
        }

        


    }
}

SpinningFish.Web/Areas/Shop/Controllers/ReelsController.cs
namespace SpinningFish.Web.Areas.Shop.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Services.Shop;
    using System.Threading.Tasks;

    public class ReelsController : BaseShopController
    {
        private readonly IReelService reels;
        private readonly IBrandService brands;

        public ReelsController(
            IReelService reels, 
            IBrandService brands)
        {
            this.reels = reels;
            this.brands = brands;
        }

        public async Task<IActionResult> All(int id)
        {
            var allReels = await this.reels.AllReelsByIdBrandAsync(id);
            
            return this.View(allReels);
        }

        public async Task<IActionResult> Details(int id)
        {
            var allReels = await this.reels.DetailsReelByIdAsync(id);

            return this.View(allReels);
        }
    }
}

SpinningFish.Web/Areas/Shop/Controllers/ShoppingCartController.cs
namespace SpinningFish.Web.Areas.Shop.Controllers
{
    using System.Collections.Generic;
    using Microsoft.AspNetCore.Mvc;
    using Data;
    using Services.Shop;
    using Models;
    using Infrastructure.Extensions;
    using System.Linq;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Data.Models;
    using Services.Shop.Models.ShoppingCart;

    public class ShoppingCartController : BaseShopController
    {
        private readonly IShoppingCartManager shoppingCartManager;
        private readonly SpinningFishDbContext db;
        private readonly UserManager<User> userManager;

        public ShoppingCartController(
            IShoppingCartManager shoppingCartManager,
            SpinningFishDbContext db,
            UserManager<User> userManager)
        {
            this.shoppingCartManager = shoppingCartManager;
            this.db = db;
            this.userManager = userManager;
        }

        public  IActionResult Items()
        {
            var shoppingCartId = this.HttpContext.Session.GetShoppingCartId();

            var items = this.shoppingCartManager.GetItems(shoppingCartId);

            var itemsWithDetails = this.GetCartItem(items);

            return this.View(itemsWithDetails);
        }

        public IActionResult AddToCart(int id)
        {
            var shoppingCartId = this.HttpContext.Session.GetShoppingCartId();

            this.shoppingCartManager.AddToCart(shoppingCartId,id);

            return RedirectToAction(nameof(this.Items));
        }

        [Authorize]
        public IActionResult FinishOrder()
        {
            var shoppingCartId = this.HttpContext.Session.GetShoppingCartId();

            var items = this.shoppingCartManager.GetItems(shoppingCartId);
            
            var itemsWithDetails = this.GetCartItem(items);

            var order = new Order
            {
                UserId = this.userManager.GetUserId(User),
                TotalPrice = itemsWithDetails.Sum(i => i.Price * i.Quantity)
            };

            foreach (var item in itemsWithDetails)
            {
                order.Items.Add(new OrderItem
                {
                    ProductId = item.ProductId,
                    ProductPrice = item.Price,
                    Quantity = item.Quantity
                });
            }

            this.db.Add(order);
            this.db.SaveChanges();

            this.shoppingCartManager.Clear(shoppingCartId);

            return RedirectToAction(nameof(Success));
        }

        public IActionResult Success()
        {
            return this.View();
        }

        private List<CartItemViewModel> GetCartItem(IEnumerable<CartItem> items)
        {
            var itemIds = items.Select(i => i.ProductId);

            var itemWithDetails = this.db
                .Reels
                .Where(pr => itemIds.Contains(pr.Id))
                .Select(pr => new CartItemViewModel
                {
                    ProductId = pr.Id,
                    Title = pr.Model,
                    Price = pr.Price,
                    Quantity = pr.Quantity
                })
                .ToList();

            var itemQuantities = items.ToDictionary(i => i.ProductId, i => i.Quantity);


            itemWithDetails.ForEach(i => i.Quantity = itemQuantities[i.ProductId]);

            return itemWithDetails;
        }  
    }
}

SpinningFish.Web/Areas/Shop/Views/Reels/All.cshtml
@model IEnumerable<ReelListingServiceModel>

@{
    ViewData["Title"] = "All";
}

<hr/>
<ul class="breadcrumb">
    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
    <li><a asp-area="Shop" asp-controller="Brands" asp-action="Index">Brands</a></li>
    <li><a asp-area="Shop" asp-controller="Reels" asp-action="All"></a></li>
</ul>

<div class="row">
@foreach (var reel in Model)
{
    <div class="col-md-3">
        <ul class="list-group">
            <li class="list-group-item" id="brand-list">
                <img src="data:image;base64,@Convert.ToBase64String(reel.Image)" style="height: 150px; width: 150px;" alt="@reel.Model"/>
                <p><a href="/shop/reels/details/@reel.Id">@reel.Model</a></p>
                <p>Price :@reel.Price bgn</p>

                <br />
            </li>
        </ul>
    </div>
}
</div>

SpinningFish.Web/Areas/Shop/Views/Reels/Details.cshtml
@model IEnumerable<ReelListingServiceModel>

@{
    ViewData["Title"] = "All";
}

<h2>All</h2>

<hr/>
<ul class="breadcrumb">
    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
    <li><a asp-area="Shop" asp-controller="Brands" asp-action="Index">Brands</a></li>
</ul>

<main>
    <div class="container">
        <div class="row">
            @foreach (var reel in Model)
            {
                <div class="col-12 text-center">

                    <h1 class="display-3">@reel.Model</h1>
                    <br/>

                    <img class="card-image-top img-fluid img-thumbnail"
                         src="data:image;base64,@Convert.ToBase64String(reel.Image)" style="height: 350px; width: 350px;" alt="@reel.Model">

                    <br />
                    <br/>
                    <p><strong>Price:</strong> - @reel.Price BGN</p>
                    <br/>
                    <a class="btn btn-primary"asp-area="Shop" asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@reel.Id">Buy</a>
                    <hr />
                    <p><strong>Description:</strong> @reel.Description</p>
                    <hr />
                    <p><strong>Details:</strong> @reel.Details</p>
                    <hr />
                    <p><strong>Category:</strong> @reel.Category</p>
                    <hr />
                    <p><strong>@reel.Model</strong> added in our catalog on @reel.АddedOnDate.ToShortDateString()
                    </p>
                    <p>

                        <iframe width="560" height="315" src="https://www.youtube.com/embed/@reel.VideoId" frameborder="0"
                                allowfullscreen></iframe>
                    </p>
                    <br/>
                    <br/>
                </div>
            }
        </div>
    </div>
</main>